name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run tests and generate coverage report
      run: |
        npm test -- --coverage > /dev/null 2>&1
        echo "Tests completed. Generating report..."
      continue-on-error: true

    - name: Check for coverage report
      run: |
        if [ -f coverage/lcov.info ]; then
          echo "Coverage report generated successfully."
        else
          echo "Coverage report not found. There might be an issue with the test run."
          exit 1
        fi

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info
      if: success()

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: coverage/lcov-report/index.html
        if-no-files-found: warn